"use client"
import { useState } from "react"
import { ArrowRight, LoaderCircle, Sparkles } from "lucide-react"
import { OutfitCard } from "@/components/outfit-card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { catalog } from "@/lib/catalog"
type Result={intro:string;recommendations:{outfitId:number;reason:string;stylingTip:string}[]}
const ideas=["Monsoon evening party","Wedding guest in Mumbai","Graduation ceremony","Luxury dinner date"]
export default function StylistPage(){const [prompt,setPrompt]=useState("");const [pending,setPending]=useState(false);const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState("");async function submit(){setPending(true);setError("");try{const response=await fetch("/api/stylist",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt})});const data=await response.json();if(!response.ok)throw new Error(data.error);setResult(data)}catch(e){setError(e instanceof Error?e.message:"Please try again.")}finally{setPending(false)}}return <div className="mx-auto min-h-[80vh] max-w-7xl px-4 py-12 md:px-8"><section className="mx-auto flex max-w-4xl flex-col items-center gap-7 text-center"><Badge variant="outline" className="border-accent text-accent"><Sparkles/> YOUR PRIVATE AI STYLIST</Badge><h1 className="text-balance font-serif text-6xl leading-[.9] md:text-8xl">Dress for the <em className="font-normal text-accent">feeling.</em></h1><p className="max-w-2xl text-pretty text-muted-foreground">Tell us where you&apos;re going, the weather, your budget, dress code or simply how you want to feel. We&apos;ll curate the look.</p><div className="w-full rounded-2xl border bg-card p-3 shadow-xl shadow-foreground/5"><Textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing&&e.keyCode!==229){e.preventDefault();submit()}}} placeholder="What are you dressing for?" className="min-h-28 resize-none border-0 bg-transparent text-lg shadow-none"/><div className="flex items-center justify-between gap-3 border-t pt-3"><span className="hidden text-xs text-muted-foreground sm:inline">Mention city, weather and budget for a sharper edit</span><Button disabled={pending||prompt.length<5} onClick={submit}>{pending?<LoaderCircle className="animate-spin" data-icon="inline-start"/>:<Sparkles data-icon="inline-start"/>}{pending?"Curating...":"Curate my looks"}<ArrowRight data-icon="inline-end"/></Button></div></div><div className="flex flex-wrap justify-center gap-2">{ideas.map(idea=><Button key={idea} variant="outline" size="sm" onClick={()=>setPrompt(idea)}>{idea}</Button>)}</div>{error&&<p className="text-sm text-destructive">{error}</p>}</section>{result&&<section className="mt-20"><div className="mx-auto mb-10 max-w-2xl text-center"><p className="text-xs uppercase tracking-[.2em] text-accent">Your personal edit</p><h2 className="mt-3 font-serif text-4xl">{result.intro}</h2></div><div className="grid gap-8 md:grid-cols-3">{result.recommendations.map(rec=>{const outfit=catalog.find(o=>o.id===rec.outfitId);if(!outfit)return null;return <div key={rec.outfitId} className="flex flex-col gap-4"><OutfitCard outfit={outfit}/><div className="rounded-xl bg-card p-4"><p className="text-sm leading-relaxed">{rec.reason}</p><p className="mt-2 text-xs text-muted-foreground"><strong>Style note:</strong> {rec.stylingTip}</p></div></div>})}</div></section>}</div>}
