"use server"
import { and, eq, gt, lt, ne } from "drizzle-orm"
import { headers } from "next/headers"
import Stripe from "stripe"
import { auth } from "@/lib/auth"
import { db } from "@/lib/db"
import { bookings, outfits } from "@/lib/db/schema"
import { catalog } from "@/lib/catalog"
export async function startBooking(input:{outfitId:number;startDate:string;endDate:string}){ const stripe=new Stripe(process.env.STRIPE_SECRET_KEY!); const session=await auth.api.getSession({headers:await headers()}); if(!session?.user) return {error:"Please sign in to reserve this look.",login:true}; const start=new Date(`${input.startDate}T00:00:00`),end=new Date(`${input.endDate}T00:00:00`); if(!Number.isInteger(input.outfitId)||isNaN(start.getTime())||isNaN(end.getTime())||end<start||start<new Date(new Date().setHours(0,0,0,0))) return {error:"Choose valid future rental dates."}; const outfit=catalog.find(o=>o.id===input.outfitId); if(!outfit)return {error:"Outfit not found."}; const conflicts=await db.select().from(bookings).where(and(eq(bookings.outfitId,input.outfitId),lt(bookings.startDate,input.endDate),gt(bookings.endDate,input.startDate),ne(bookings.status,"cancelled"))).limit(1); if(conflicts.length)return {error:"This outfit is already booked during your selected dates."}; const days=Math.floor((end.getTime()-start.getTime())/86400000)+1; if(days>14)return {error:"Rental duration cannot exceed 14 days."}; const totalPaise=outfit.pricePerDay*days*100; const [booking]=await db.insert(bookings).values({userId:session.user.id,outfitId:outfit.id,startDate:input.startDate,endDate:input.endDate,totalPaise}).returning(); const origin=(await headers()).get("origin")||process.env.BETTER_AUTH_URL||"http://localhost:3000"; const checkout=await stripe.checkout.sessions.create({mode:"payment",line_items:[{price_data:{currency:"inr",unit_amount:totalPaise,product_data:{name:`${outfit.name} · ${days} day rental`,description:`${input.startDate} to ${input.endDate}`}},quantity:1}],customer_email:session.user.email,success_url:`${origin}/dashboard?booking=confirmed`,cancel_url:`${origin}/outfits/${outfit.slug}?booking=cancelled`,metadata:{bookingId:String(booking.id),userId:session.user.id}},{idempotencyKey:`booking-${booking.id}`}); await db.update(bookings).set({stripeSessionId:checkout.id}).where(and(eq(bookings.id,booking.id),eq(bookings.userId,session.user.id))); return {url:checkout.url}; }
