import Image from "next/image"
import Link from "next/link"
import { ArrowRight, CalendarDays, Leaf, ShieldCheck, Sparkles } from "lucide-react"
import { OutfitCard } from "@/components/outfit-card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { catalog } from "@/lib/catalog"
export default function Home(){return <>
<section className="mx-auto max-w-7xl px-4 py-5 md:px-8"><div className="grid min-h-[76vh] overflow-hidden rounded-3xl bg-card md:grid-cols-[1.05fr_.95fr]"><div className="flex flex-col justify-center gap-7 p-7 md:p-14"><Badge variant="outline" className="w-fit border-accent text-accent">THE NEW CIRCULAR WARDROBE</Badge><div className="flex flex-col gap-4"><h1 className="max-w-2xl text-balance font-serif text-6xl leading-[.88] tracking-[-.04em] md:text-8xl">Rent luxury.<br/><em className="font-normal text-accent">Wear confidence.</em></h1><p className="max-w-lg text-pretty text-base leading-relaxed text-muted-foreground md:text-lg">AI-curated designer fashion for weddings, celebrations and every moment worth dressing for.</p></div><div className="flex flex-wrap gap-3"><Button size="lg" nativeButton={false} render={<Link href="/collection"/>}>Browse collection <ArrowRight data-icon="inline-end"/></Button><Button size="lg" variant="outline" nativeButton={false} render={<Link href="/stylist"/>}><Sparkles data-icon="inline-start"/>Try AI Stylist</Button></div><div className="flex flex-wrap gap-5 text-xs uppercase tracking-widest text-muted-foreground"><span>Delivery across Mumbai</span><span>Authenticity assured</span></div></div><div className="relative min-h-[55vh] md:min-h-0"><Image src="/images/hero-fashion.png" alt="Model wearing a sculptural black evening gown" fill priority className="object-cover" sizes="(max-width:768px) 100vw, 50vw"/><div className="absolute bottom-5 left-5 rounded-xl border border-border/30 bg-background/75 p-4 backdrop-blur-md"><p className="text-xs uppercase tracking-widest text-muted-foreground">Curated edit</p><p className="font-serif text-xl">After Dark / Mumbai</p></div></div></div></section>
<section className="mx-auto max-w-7xl px-4 py-20 md:px-8"><div className="mb-10 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-3 text-xs uppercase tracking-[.25em] text-accent">The occasion edit</p><h2 className="font-serif text-4xl md:text-6xl">Trending now</h2></div><Button variant="link" render={<Link href="/collection"/>}>View all pieces <ArrowRight data-icon="inline-end"/></Button></div><div className="grid grid-cols-2 gap-4 md:grid-cols-4 md:gap-6">{catalog.map(outfit=><OutfitCard key={outfit.id} outfit={outfit}/>)}</div></section>
<section id="how-it-works" className="bg-foreground text-background"><div className="mx-auto max-w-7xl px-4 py-20 md:px-8"><div className="grid gap-12 md:grid-cols-2"><div><p className="mb-3 text-xs uppercase tracking-[.25em] text-accent">Effortless by design</p><h2 className="text-balance font-serif text-5xl md:text-7xl">A dream wardrobe, without the wardrobe.</h2></div><div className="grid gap-8 sm:grid-cols-3">{[[Sparkles,"01","Get styled","Tell our AI where you are going and how you want to feel."],[CalendarDays,"02","Choose dates","Reserve your look with real-time date availability."],[ShieldCheck,"03","Wear & return","Your piece arrives ready to wear. Return it after your moment."]].map(([Icon,n,t,d])=><div key={String(n)} className="flex flex-col gap-3"><Icon className="text-accent"/><span className="text-xs text-background/50">{String(n)}</span><h3 className="font-serif text-2xl">{String(t)}</h3><p className="text-sm leading-relaxed text-background/60">{String(d)}</p></div>)}</div></div></div></section>
<section className="mx-auto max-w-7xl px-4 py-20 md:px-8"><div className="grid overflow-hidden rounded-3xl bg-card md:grid-cols-2"><div className="relative min-h-96"><Image src="/images/emerald-sari.png" alt="Emerald silk sari from the circular collection" fill className="object-cover" sizes="50vw"/></div><div className="flex flex-col justify-center gap-6 p-8 md:p-14"><Leaf className="text-accent"/><p className="text-xs uppercase tracking-[.25em] text-accent">Style with impact</p><h2 className="font-serif text-5xl">One outfit.<br/>Many stories.</h2><p className="leading-relaxed text-muted-foreground">Every rental extends the life of remarkable design while reducing the water, waste and carbon hidden inside a one-time purchase.</p><div className="grid grid-cols-3 gap-4 border-t pt-6"><div><strong className="font-serif text-3xl">68%</strong><p className="text-xs text-muted-foreground">less impact</p></div><div><strong className="font-serif text-3xl">12k</strong><p className="text-xs text-muted-foreground">wears shared</p></div><div><strong className="font-serif text-3xl">4.9</strong><p className="text-xs text-muted-foreground">community rating</p></div></div></div></div></section>
</>}
