"use client"
import Link from "next/link"
import { Heart, Menu, Moon, Search, Sparkles, Sun, UserRound } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet"
import { useTheme } from "@/components/theme-provider"

const links = [["Collection","/collection"],["AI Stylist","/stylist"],["How it works","/#how-it-works"],["Our story","/about"]]
export function SiteHeader(){ const { resolvedTheme, setTheme } = useTheme(); return <header className="sticky top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 md:px-8"><Link href="/" className="flex items-center gap-2" aria-label="LuxeLoop AI home"><span className="flex size-8 items-center justify-center rounded-full border border-accent font-serif text-sm">L</span><span className="font-serif text-xl tracking-tight">LuxeLoop <span className="text-accent">AI</span></span></Link><nav className="hidden items-center gap-7 md:flex" aria-label="Main navigation">{links.map(([label,href])=><Link key={href} href={href} className="text-sm text-muted-foreground transition-colors hover:text-foreground">{label}</Link>)}</nav><div className="flex items-center gap-1"><Button variant="ghost" size="icon" aria-label="Search collection" nativeButton={false} render={<Link href="/collection"/>}><Search/></Button><Button variant="ghost" size="icon" aria-label="Toggle color theme" onClick={()=>setTheme(resolvedTheme === "dark" ? "light" : "dark")}>{resolvedTheme === "dark" ? <Sun/> : <Moon/>}</Button><Button variant="ghost" size="icon" className="hidden sm:inline-flex" aria-label="Your wishlist" nativeButton={false} render={<Link href="/dashboard"/>}><Heart/></Button><Button variant="ghost" size="icon" className="hidden sm:inline-flex" aria-label="Your account" nativeButton={false} render={<Link href="/login"/>}><UserRound/></Button><Sheet><SheetTrigger render={<Button variant="ghost" size="icon" className="md:hidden" aria-label="Open menu"/>}><Menu/></SheetTrigger><SheetContent><SheetTitle className="font-serif">LuxeLoop AI</SheetTitle><nav className="flex flex-col gap-5 p-5">{links.map(([label,href])=><Link key={href} href={href} className="text-lg">{label}</Link>)}<Button nativeButton={false} render={<Link href="/stylist"/>}><Sparkles data-icon="inline-start"/>Try AI Stylist</Button></nav></SheetContent></Sheet></div></div></header> }
