import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { notFound } from "next/navigation"
import { ChevronLeft, Heart, Star } from "lucide-react"
import { BookingPanel } from "@/components/booking-panel"
import { OutfitCard } from "@/components/outfit-card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { catalog, getOutfit } from "@/lib/catalog"
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const outfit=getOutfit(slug);return{title:outfit?.name??"Outfit",description:outfit?.description}}
export default async function OutfitPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const outfit=getOutfit(slug);if(!outfit)notFound();return <div className="mx-auto max-w-7xl px-4 py-8 md:px-8"><Button variant="ghost" nativeButton={false} render={<Link href="/collection"/>}><ChevronLeft data-icon="inline-start"/>Back to collection</Button><div className="mt-5 grid gap-10 lg:grid-cols-[1.2fr_.8fr]"><div className="grid gap-4 md:grid-cols-2"><div className="relative aspect-[4/5] overflow-hidden rounded-2xl bg-muted md:col-span-2"><Image src={outfit.image} alt={outfit.name} fill priority className="object-cover" sizes="66vw"/></div></div><div className="flex flex-col gap-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-muted-foreground">{outfit.brand}</p><h1 className="mt-2 font-serif text-5xl md:text-6xl">{outfit.name}</h1></div><Button variant="outline" size="icon" aria-label="Save outfit"><Heart/></Button></div><div className="flex flex-wrap items-center gap-3"><Badge>{outfit.occasion}</Badge><span className="flex items-center gap-1 text-sm"><Star className="fill-current text-accent"/> {outfit.rating} · 48 reviews</span></div><p className="leading-relaxed text-muted-foreground">{outfit.description}</p><Separator/><div><h2 className="mb-3 font-medium">Available sizes</h2><div className="flex gap-2">{outfit.sizes.map(size=><Badge key={size} variant="outline" className="px-4 py-2">{size}</Badge>)}</div></div><div className="grid grid-cols-2 gap-5 text-sm"><div><p className="text-muted-foreground">Designer</p><p>{outfit.brand}</p></div><div><p className="text-muted-foreground">Colour</p><p>{outfit.color}</p></div><div><p className="text-muted-foreground">Fit</p><p>True to size</p></div><div><p className="text-muted-foreground">Care</p><p>Professionally cleaned</p></div></div><BookingPanel outfit={outfit}/></div></div><section className="py-20"><h2 className="mb-8 font-serif text-4xl">You may also love</h2><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{catalog.filter(o=>o.id!==outfit.id).slice(0,3).map(o=><OutfitCard key={o.id} outfit={o}/>)}</div></section></div>}